### ISSUE TITLE
please god make gas powered thrusters connect to atmos pipes and not take atmos from a turf

### ISSUE THREAD

**Issue by Paxilmaniac** [Willardstation/tg-voidcrew#24]
## Reproduction:
lol, lmao
![image](https://user-images.githubusercontent.com/82386923/186029444-cc4c8136-8c2d-4384-a61f-83e068abee50.png)

**Comment by JohnFulpWillard** [comment]
I want them to work like a Turbine, so I disagree with this.

**Comment by ZephyrTFA** [comment]
I technically did this with the overmap PR lmao

**Comment by ZephyrTFA** [comment]
@JohnFulpWillard
