### ISSUE TITLE
Readying up spawns you in the error handling room

### ISSUE THREAD

**Issue by unit0016** [willardstation/tg-voidcrew#56]
See title - Shiptest/Voidcrew had readying up disabled, ostensibly to protect against this - maybe there's a better solution?

**Comment by JohnFulpWillard** [comment]
I think we have 2 options:

1. we disable readying up and the job prefs menu
2. we let people ready up for the roundstart ship, I don't know how well we can support this (currently it doesn't spawn because it keeps selecting broken ships) but it might be preferable?

**Comment by SuperNovaa41** [comment]
The reason is because there is no landmark for spawning right now. we should disable readying up yes, but the reason isn't due to the fact that we have that, its just that there is literally no place to spawn
