### ISSUE TITLE
A functional Cargo

### ISSUE THREAD

**Issue by JohnFulpWillard** [Willardstation/tg-voidcrew#7]

**Comment by PeriodicChaos** [comment]
we have this already as well don't forget the express cargo computer is a thing

**Comment by JohnFulpWillard** [comment]
we currently only have TG's cargo which isn't gonna work for what we want.

**Comment by PeriodicChaos** [comment]
Little confused unless you want a shuttle to dock to a ship from space else we could do the same thing done before use the express cargo computer for getting our stuff

**Comment by JohnFulpWillard** [comment]
I mostly explained it in https://hackmd.io/4xy7l9v4RX2a-gD9aWiNTw?view

Basically a mix of Shiptest and NSV cargo. A 3x3 cargo room that counts as the 'cargo ship' that will be beamed up/down for sending off and purchasing with the default cargo shuttle timer, for every individual ship.
